spring:
  profiles:
    active: dev

  application:
    name: ecom-api
    image-dir: images
    jwt-cookie: jwt

frontend:
  url: "http://localhost:5173"

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml