server:
  port: 5000

spring:
  application:
    security:
      jwt-secret: "TmOENcLVa0BC+ksw8z7250dQ5eUxPVZ6nP/A3+Pnt2uWZ8FA5XjKsuf3u+gG0I+z"
      jwt-expiration: 30000000

  datasource:
    url: "jdbc:postgresql://shopsphere.cdu42a4u872r.us-east-1.rds.amazonaws.com:5432/postgres"
    username: "postgres"
    password: "Yasu2237451"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"